import { MS_PER_SECOND } from './timing';

// Clear sequence branch threshold.
export const SPECIAL_CLEAR_FISH_THRESHOLD = 15;

// Clear / ending timing constants.
export const SPECIAL_FIN_SWAP_MS = 1000;
export const CLEAR_ICON_SWAP_MS = 1000;
export const CLEAR_BOSS_EXIT_MS = 3200;
export const CLEAR_BOSS_GROUND_SETTLE_MS = 300;
export const CLEAR_BOSS_GROUND_PAUSE_MS = 2000;
export const CLEAR_BOSS_PRE_EXIT_JUMP_COUNT = 3;
export const CLEAR_BOSS_PRE_EXIT_JUMP_UP_MS = 170;
export const CLEAR_BOSS_PRE_EXIT_JUMP_DOWN_MS = 200;
export const CLEAR_BOSS_PRE_EXIT_JUMP_HEIGHT_PX = 14;
export const CLEAR_BOSS_PRE_EXIT_JUMP_CYCLE_MS =
  CLEAR_BOSS_PRE_EXIT_JUMP_UP_MS + CLEAR_BOSS_PRE_EXIT_JUMP_DOWN_MS;
export const CLEAR_BOSS_PRE_EXIT_JUMP_TOTAL_MS =
  CLEAR_BOSS_PRE_EXIT_JUMP_CYCLE_MS * CLEAR_BOSS_PRE_EXIT_JUMP_COUNT;
export const CLEAR_BOSS_EXIT_START_DELAY_MS =
  CLEAR_BOSS_GROUND_SETTLE_MS + CLEAR_BOSS_GROUND_PAUSE_MS + CLEAR_BOSS_PRE_EXIT_JUMP_TOTAL_MS;
export const CLEAR_BOSS_TOTAL_EXIT_MS = CLEAR_BOSS_EXIT_START_DELAY_MS + CLEAR_BOSS_EXIT_MS;
export const CLEAR_BOSS_EXIT_TRANSLATE_X = '140%';
const CLEAR_PLAYER_MOVE_BASE_MS = 2800;
const CLEAR_PLAYER_MOVE_SPEED_MULTIPLIER = 1.2;
export const CLEAR_PLAYER_MOVE_MS = CLEAR_PLAYER_MOVE_BASE_MS / CLEAR_PLAYER_MOVE_SPEED_MULTIPLIER;
export const CLEAR_PLAYER_FADE_MS = 300;
export const SPECIAL_ROCKET_ENTRY_MOVE_MS = 1200;
export const MIN_SPECIAL_ROCKET_ENTRY_MOVE_MS = 600;
export const ROCKET_ENTRY_DISTANCE_RATIO = 0.5;
export const SPECIAL_ROCKET_ENTRY_SPEED_PERCENT = 70;
export const SPECIAL_ROCKET_ENTRY_MOVE_DURATION_MULTIPLIER =
  100 / SPECIAL_ROCKET_ENTRY_SPEED_PERCENT;
export const SPECIAL_ROCKET_ENTRY_PLAYER_DELAY_MS = 500;
export const SPECIAL_APPROACH_MOVE_MS = 3000;
export const SPECIAL_APPROACH_HOLD_MS = 2000;
export const DESKTOP_SPECIAL_APPROACH_MOVE_DURATION_MULTIPLIER = 2.0;
export const MOBILE_SPECIAL_APPROACH_EXTRA_DELAY_MS = 500;
export const MOBILE_SPECIAL_APPROACH_MOVE_DURATION_MULTIPLIER = 2;
export const SPECIAL_STEP_MS = 1500;
export const SPECIAL_BYE_DISPLAY_MS = SPECIAL_STEP_MS + 1000;
export const SPECIAL_FLY_PREP_MS = 2000;
export const SPECIAL_FLYOUT_MS = 6800;
export const SPECIAL_FIN_DELAY_MS = 2000;

// Player placement constants during clear sequence.
export const FRAME_RATE = 60;
export const FALLBACK_GAME_WIDTH_PX = 1200;
export const FALLBACK_APPROACH_DISTANCE_RATIO = 0.45;
export const ROCKET_TARGET_CENTER_X_RATIO = 0.5;
export const PLAYER_APPROACH_ALIGNMENT_WIDTH_RATIO = 1.1;
export const MIN_SPECIAL_APPROACH_MOVE_MS = 280;
export const PLAYER_OPACITY_TRANSITION = 'opacity 0.3s ease';
export const PLAYER_VISIBLE_OPACITY = '1';
export const PLAYER_HIDDEN_OPACITY = '0';
export const PLAYER_VISIBLE_VISIBILITY = 'visible';
export const PLAYER_HIDDEN_VISIBILITY = 'hidden';
export const PLAYER_CENTER_LEFT = '50%';
export const PLAYER_TRANSLATE_NONE = 'translateX(0)';
export const PLAYER_TRANSLATE_TO_ROCKET = 'translateX(-110%)';
export const PLAYER_TRANSLATE_CENTER = 'translateX(-50%)';

export { MS_PER_SECOND };
