import { BOSS_ATTACK_SPRITES } from './assets';
import {
  BASELINE_GAME_HEIGHT as BASELINE_GAME_HEIGHT_METRIC,
  FALLBACK_GAME_HEIGHT as FALLBACK_GAME_HEIGHT_METRIC,
  FALLBACK_GAME_WIDTH as FALLBACK_GAME_WIDTH_METRIC,
} from './metrics';
import { MS_PER_SECOND as BASE_MS_PER_SECOND } from './timing';

// Arm and collision timing constants.
export const ARM_HOLD_MS = 120;
export const MS_PER_SECOND = BASE_MS_PER_SECOND;

// Baseline geometry used to convert model units to viewport-scaled px values.
export const BASELINE_GAME_HEIGHT = BASELINE_GAME_HEIGHT_METRIC;
export const FALLBACK_GAME_HEIGHT = FALLBACK_GAME_HEIGHT_METRIC;
export const FALLBACK_GAME_WIDTH = FALLBACK_GAME_WIDTH_METRIC;
export const BASELINE_BOSS_BASE_WIDTH = 208;
export const BASELINE_ARM_RIGHT_OFFSET = 12;
export const MOBILE_BOSS_RIGHT_SHIFT_BASELINE_PX = 20;

// Boss entry / animation parameters.
export const BOSS_ENTRY_DURATION_MS = 1300;
export const BOSS_ENTRY_OFFSET_MULTIPLIER = 1.1;
export const ARM_HIT_START_PROGRESS_RATIO = 0.45;
export const MOBILE_ARM_HIT_START_PROGRESS_RATIO = 0.6;
export const ARM_HITBOX_BASE_WIDTH_OFFSET_RATIO = 0.8;
export const ARM_HITBOX_FRONT_PADDING_RATIO = 0.06;
export const ARM_HITBOX_FRONT_PADDING_MAX_PX = 18;
export const ARM_HITBOX_VERTICAL_OFFSET_RATIO = 0.3;
export const MOBILE_ARM_HITBOX_VERTICAL_OFFSET_RATIO = 0.6;
export const ARM_EXTEND_FAST_FROM_FRAME_NUMBER = 16;
export const ARM_EXTEND_FAST_TO_FRAME_NUMBER = 20;
export const ARM_EXTEND_FAST_SPEED_MULTIPLIER = 2;
export const ARM_RETRACT_FAST_FROM_FRAME_NUMBER = 12;
export const ARM_RETRACT_FAST_TO_FRAME_NUMBER = 20;
export const ARM_RETRACT_FAST_SPEED_MULTIPLIER = 2;
export const ARM_RETRACT_SPEED_MULTIPLIER = 1.5;
export const PC_BOSS_ATTACK_SPEED_MULTIPLIER = 2;
export const PC_BOSS_RETRACT_SPEED_MULTIPLIER = 1.2;
export const MOBILE_BOSS_ATTACK_SPEED_MULTIPLIER = 0.125;
export const MOBILE_BOSS_ARM_SPEED_BOOST_MULTIPLIER = 1.5;
const MOBILE_BOSS_ATTACK_MAX_FRAME_NUMBER = 6;
export const MOBILE_BOSS_ATTACK_MAX_FRAME_INDEX = MOBILE_BOSS_ATTACK_MAX_FRAME_NUMBER - 1;
export const MOBILE_BOSS_ATTACK_LENGTH_RATIO =
  MOBILE_BOSS_ATTACK_MAX_FRAME_NUMBER / BOSS_ATTACK_SPRITES.length;
export const MOBILE_ARM_EXTEND_FAST_FROM_FRAME_NUMBER = 4;
export const MOBILE_ARM_EXTEND_FAST_TO_FRAME_NUMBER = 6;
export const MOBILE_ARM_RETRACT_FAST_FROM_FRAME_NUMBER = 1;
export const MOBILE_ARM_RETRACT_FAST_TO_FRAME_NUMBER = 6;
export const BOSS_PATTERN_ONE_REPEAT_BEFORE_PATTERN_TWO = 2;
export const BOSS_PATTERN_TWO_RANDOM_RATE = 0.45;
export const BOSS_PATTERN_TWO_HOLD_MS = MS_PER_SECOND * 10;
const BOSS_PATTERN_TWO_FLOAT_OFFSET_REM = 10;
export const BOSS_PATTERN_TWO_LIFT_DURATION_MS = 1100;
export const BOSS_MODE_TRIGGER_WINDOW_SECONDS = 1;
export const OBSTACLE_PLAYER_PROXIMITY_CHECK_PX = 100;
export const DEFAULT_OBSTACLE_HITBOX_SCALE = 1;
export const PLAYER_HIDDEN_OPACITY = '0';
export const PLAYER_HIDDEN_VISIBILITY = 'hidden';
export const ZERO_WIDTH_PX = '0px';
export const BOSS_RESET_TRANSLATE_X = 'translateX(0px)';
export const MOBILE_BOSS_RIGHT_MARGIN_MIN_PX = 8;
export const MOBILE_BOSS_RIGHT_MARGIN_RATIO = 0.02;
export const ARM_FRAME_BASE_DURATION_MS = MS_PER_SECOND / 60;
export const ARM_FRAME_DELTA_MIN_SCALE = 0.5;
export const ARM_FRAME_DELTA_MAX_SCALE = 2.5;

// Boss idle bob settings.
export const BOSS_BASE_SPRITE_SWAP_MS = (MS_PER_SECOND / 3) * 2;
export const BOSS_WAIT_BOB_CYCLE_MS = MS_PER_SECOND * 3;
export const BOSS_WAIT_BOB_AMPLITUDE = 24;
const BOSS_WAIT_BOB_EXTRA_UP_REM = 5;
const REM_IN_PX = 16;
export const BOSS_WAIT_BOB_EXTRA_UP_PX = BOSS_WAIT_BOB_EXTRA_UP_REM * REM_IN_PX;
export const BOSS_WAIT_GROUND_THRESHOLD = 0.12;
export const BOSS_WAIT_ATTACK_CHARGE_MS = 500;
export const MOBILE_BOSS_WAIT_ATTACK_CHARGE_MS = 2000;
export const PATTERN_ONE_POST_ATTACK_WAIT_MS = 500;
export const BOSS_PATTERN_TWO_FLOAT_OFFSET_PX = BOSS_PATTERN_TWO_FLOAT_OFFSET_REM * REM_IN_PX;
export const BOSS_PATTERN_TWO_POST_ATTACK_SETTLE_MS = 280;
